const SYSTEM_PROMPT = "You are an editor and translator with more than 20 years of experience. "
const SYSTEM_PROMPT_INSTRUCTIONS = "I will provide you a current section of text marked with the following: <current><original></original></current>. I may also include the previous section of text to the current text which will be marked with <prev><original></original><rewrite></rewrite></prev>. An example of a previous section would look like <prev><original>We is have lots of fun tonight!</original><rewrite>We are going to have lots of fun tonight!</rewrite></prev>\n" +
"I will first give you instructions on how to provide a <outline> of the text. After you return the outline, I give you instructions on how to provide the full <rewrite>.";

// const KOREAN = "You are cleaning up a translation of a fantasy web novel from the original Korean into English. The first pass of translation has been done, you are now going to go rewrite it to make it more clear to a US english speaking audience. Your rewrite will be more idiomatic, fix any grammar mistakes, make it more clear who is speaking when there is dialog, and change references to Korean cultural norms so they are understandable to a US audience. You may also expand descriptions or details to add clarity to the writing.\n"

const CHAIN = ["Write out a numbered list that is a description of every sentence in the <current> tag. Do not include the text inside the <prev> tag. At the beginning mark the perspective of the text and mark of any time the perspective changes. Every line or sentence inside the <current><original> tag should be included. If the line has descriptive words, make sure to include the specific descriptors used and what is being described. If there are quotes, list who is saying the quote if it is possible to tell. Any feelings or emotions that are written or hinted at should be included in the details of a line. If there is a chapter start or ending, mark that with the chapter name if possible, and begin or end. Keep this description in a <outline> tag.",
"Using the outline inside the <outline> tag as a base, write out the story in English. Add detail to descriptions and actions as needed to fit the <<style>> style of the writing and the style within the <prev><rewrite> tag if that exists.  If the writing is in first person, use first person I/me pronouns. If the perspective is 3rd person, use proper third person pronouns and proper names. If the perspective shifts, mark that with *** on its own line. If there is a chapter break, mark that with *Chapter* on its own line. Put this rewrite into a <rewrite> tag. Do not include any of the <prev> text in the rewrite."];

const MODEL_SMALL = "claude-3-haiku-20240307";
const MODEL_MEDIUM = "claude-3-sonnet-20240229";
const MODEL_LARGE = "claude-3-opus-20240229";

export { SYSTEM_PROMPT, CHAIN, MODEL_SMALL, MODEL_MEDIUM, MODEL_LARGE, SYSTEM_PROMPT_INSTRUCTIONS};